lagoon-sync:
  mariadb:
    config:
      ignore-table-data:
        - "cache_data"
        - "cache_menu"
  files:
    config:
      sync-directory: "/app/web/sites/default/files"
    local:
      config:
        sync-directory: "/var/www/html/web/sites/default/files"
