<?php

/**
 * @file
 * Provides a composite element to capture limited person info. Namely
 * first name, last name and date of birth.
 *
 * We are going with a custom module (Webform element and plugin) in order
 * to be able to format the results easily.
 */

module_load_include('inc', 'webform', 'includes/webform.theme.template');

/**
 * Implements hook_theme().
 */
function webform_composite_simple_person_info_theme() {
  return [
    'webform_composite_simple_person_info' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for composite simple person info templates.
 *
 * Default template: webform-composite-simple-person-info.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_webform_composite_simple_person_info(array &$variables) {
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}
