<?php
use Drupal\menu_link_content\Entity\MenuLinkContent;

function biz_new_content_entity_translation_create(\Drupal\Core\Entity\EntityInterface $translation) {
    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();
    if(in_array("administrator", $roles)){
        $translation->moderation_state = "published";
    }
}
function biz_new_content_entity_create(\Drupal\Core\Entity\EntityInterface $translation) {
    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();
    if(in_array("administrator", $roles)){
        $translation->moderation_state = "published";
    }
}